<?php

/**
 * @file
 * Used to configure the advanced search form and other search behaviour.
 *
 * @author Nesta Campbell <nesta.campbell@gmail.com>
 * @todo Look at multiple hierarchy taxonomies
 *
 */

/**
 * Implementation of hook_perm()
 *
 * Allow the displaying of form fields per role.
 */
function search_config_perm() {
  return array(
    'search by node type' => array(
      'title' => t('Search by node type'),
      'description' => t('Allow users to search for content based on node type.'),
      ), 
    'search by category' => array(
      'title' => t('Search by category'),
      ), 
    'use keyword search' => array(
      'title' => t('Perform keyword search'),
      ),
    );
}


function search_config_form_search_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['search_config'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced search configuration'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  // Keyword boxes:
  $form['search_config']['keywords'] = array(
    '#type' => 'fieldset',
    '#title' => t('Keywords'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE ,
    '#description' => t('Configuration for which keyword search fields should not be displayed.')
  );

  $form['search_config']['keywords']['search_config_disable_or'] = array(
    '#type' => 'checkbox',
    '#title' => t('Containing any of the words'),
    '#default_value' => variable_get('search_config_disable_or', 0)
  );

  $form['search_config']['keywords']['search_config_disable_phrase'] = array(
    '#type' => 'checkbox',
    '#title' => t('Containing the phrase'),
    '#default_value' => variable_get('search_config_disable_phrase', 0)
  );

  $form['search_config']['keywords']['search_config_disable_negative'] = array(
    '#type' => 'checkbox',
    '#title' => t('Containing none of the words'),
    '#default_value' => variable_get('search_config_disable_negative', 0)
  );

  // Taxonomy box
  if ($taxonomy = module_invoke('taxonomy', 'form_all', 1)) {
    $form['search_config']['category'] = array(
      '#type' => 'fieldset',
      '#title' => t('Categories'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE ,
      '#description' => t('Categories to display')
    );

    $form['search_config']['category']['search_config_disable_category_all'] = array(
      '#type' => 'checkbox',
      '#title' => t('Disable category search'),
      '#default_value' => variable_get('search_config_disable_category_all', 0)
    );

    $form['search_config']['category']['search_config_disable_category'] = array(
      '#type' => 'select',
      '#title' => t('Categories'),
      '#options' => $taxonomy,
      '#size' => 10,
      '#multiple' => TRUE,
      '#default_value' => variable_get('search_config_disable_category', array()),
      '#description' => t('Disable searching by the selected categories')
    );
  }

  // Node types
  $types = node_type_get_names();
  $types = array_merge(array('all' => 'Disable all'), $types);

  $form['search_config']['type'] = array(
    '#type' => 'fieldset',
    '#title' => t('Node types'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE ,
  );

  $form['search_config']['type']['form'] = array(
    '#type' => 'fieldset',
    '#title' => t('Search Form'),
    '#collapsible' => FALSE,
    '#description' => t('Node types that users shouldn\'t be allowed to search by using the the advanced search form.')
  );

  $form['search_config']['type']['form']['search_config_disable_type'] = array(
    '#type' => 'checkboxes',
    '#options' => $types,
    '#default_value' => variable_get('search_config_disable_type', array())
  );

  $form['search_config']['type']['index'] = array(
    '#type' => 'fieldset',
    '#title' => t('Search Index'),
    '#collapsible' => FALSE,
    '#description' => t('Node types that should not be index by the search module. Any node type set to not be indexed will also be removed from the search form. If you select all available node types to not be index then the search module will be rendered unusable as no nodes will be indexed.')
  );

  // If all node types are disabled then the search module is useless.
  unset($types['all']);
  reset($types);

  $form['search_config']['type']['index']['search_config_disable_index_type'] = array(
    '#type' => 'checkboxes',
    '#options' => $types,
    '#default_value' => variable_get('search_config_disable_index_type', array())
  );
  $form['#validate'][] = 'search_config_validate';
}

/**
 * Implementation of hook_form_alter()
 */
function search_config_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_form') {
    // Keywords
    if (user_access('use keyword search')) {
      if (variable_get('search_config_disable_or', 0)) {
        unset($form['advanced']['keywords']['or']);
      }
      if (variable_get('search_config_disable_phrase', 0)) {
        unset($form['advanced']['keywords']['phrase']);
      }
      if (variable_get('search_config_disable_negative', 0)) {
        unset($form['advanced']['keywords']['negative']);
      }
    }
    // Remove all the keyword search fields
    else {
      unset($form['advanced']['keywords']);
    }

    // Node types
    // We will need to rebuild the checkboxes for the node types
    $remove = variable_get('search_config_disable_type', array());

    if ($remove['all'] || !user_access('search by node type')) {
      unset($form['advanced']['type']);
    }
    else {
      $types = node_type_get_types();

      foreach ($types as $module => $type) {
        if ($remove[$module]) {
          unset($types[$module]);
        }
        else {
          $types[$module] = t($type);
        }
      }

      // Rebuild form item -- copied from node.module, but only if advanced
      // fieldset exists.
      if (!empty($form['advanced'])) {
        if (count($types) == 1) {
          $type_keys = array_keys($types);
          $form['advanced']['type'] = array(
            '#type' => 'hidden',
            '#default_value' => $type_keys[0],
          );
        }
        else {
          $form['advanced']['type'] = array(
            '#type' => 'checkboxes',
            '#title' => t('Only of the type(s)'),
            '#prefix' => '<div class="criterion">',
            '#suffix' => '</div>',
            '#options' => $types,
          );
        }
      }
    }

    if ($taxonomy = module_invoke('taxonomy', 'form_all', 1)) {
      // Taxonomy
      if (variable_get('search_config_disable_category_all', 0) || !user_access('search by category')) {
        unset($form['advanced']['category']);
      }
      else {
        $terms = variable_get('search_config_disable_category', array());

        if (module_exists('og_vocab')) {
          $groupnode = og_get_group_context();
          $sql = "SELECT t.tid FROM ({vocabulary} v, {term_data} t) LEFT JOIN {og_vocab} ov ON v.vid = ov.vid WHERE (v.module = 'og_vocab' AND ov.nid != %d) AND t.vid=v.vid";
          $result = db_query($sql, $groupnode->nid);

          while ($row = db_fetch_object($result)) {
            $terms[$row->tid] = $row->tid;
          }
        }

        // FIXME: What about multiple hierarchy categories?
        foreach ($taxonomy as $vocab => $term) {
          foreach ($term as $k => $v) {
            if(in_array($k, $terms)) {
              unset($taxonomy[$vocab][$k]);
            }
          }
          // Remove empty vocabs
          if (count($taxonomy[$vocab]) == 0) {
            unset($taxonomy[$vocab]);
          }
        }

        if (count($taxonomy) == 0) {
          unset($form['advanced']['category']);
        }
        else {
          // Taxonomy box:
          $form['advanced']['category'] = array(
            '#type' => 'select',
            '#title' => t('Only in the category(s)'),
            '#prefix' => '<div class="criterion">',
            '#size' => 10,
            '#suffix' => '</div>',
            '#options' => $taxonomy,
            '#multiple' => TRUE,
          );
        }
      }
    }
  }
}

/**
 * Process a block search form submission.
 *
 * Taken from the core search module. It allows the search block to work
 * with other default search types than node.
 */
function search_config_form_submit($form, &$form_state) {
  $form_id = $form['form_id']['#value'];
  $type = $form['module']['#value'];
  $form_state['redirect'] = 'search/'. $type .'/'. trim($form_state['values'][$form_id]);
}



function search_config_validate($form, &$form_state) {
  if ($form_state['values']['form_id'] == 'search_admin_settings' && $form_state['values']['op'] == t('Save configuration')) {
    $post_values = $form_state['values'];
    $node_types = array_keys(node_type_get_types());
    
    if (!isset($post_values['search_config_disable_index_type'])) {
      return;
    }

    $index_types = array_filter($post_values['search_config_disable_index_type']);

    if (!isset($post_values['search_config_disable_type'])) {
      $post_values['search_config_disable_type'] = array();
    }

    $form_types = array_filter($post_values['search_config_disable_type']);

    if (count($index_types) != 0 && count($index_types) == count($node_types)) {
      form_set_error('search_config_disable_index_type', t('You can not set all node types to be not indexed by the search module. Disable the search module if that is what you want.'));
    }

    if (!empty($form_types['all'])) {
      return;
    }

    $type_diff = array_diff($index_types, $form_types);

    if (count($type_diff)) {
      $node_errors = array();

      foreach ($type_diff as $type) {
        $node_errors[] = $node_types[$type];
      }

      form_set_error('search_config_disable_type', t('Search index node types do not match form node types. Please check the setting for %nodes.', array('%nodes' => implode(', ', $node_errors))));
    }
 }
}

/**
 * Rewrite the search query to exclude selected node types.
 *
 * Based on the "Hiding Content from Drupal's Search System"
 * @see http://www.lullabot.com/articles/hiding-content-drupals-search-system
 * @see http://drupal.org/node/111744 if you want to help get something
 * sensible into core.
 */
function search_config_query_alter(QueryAlterableInterface $query) {
  $tables = $query->getTables();
  $search = array(
    'i' => 'search_index',
    'n' => 'node',
    );
  $intersection = array_intersect_key($search, $tables);
  if (empty($intersection)) {
    return;
  }
  // Double check to ensure that the i and n aliases are pointing to 
  // the search index and node table.
  foreach ($intersection as $alias => $info) {
    if ($tables[$alias]['table'] != $info) {
      return;
    }
  }
  
  $hidden_content_types = variable_get('search_config_disable_index_type', array());
  $hidden_content_types = array_filter($hidden_content_types);
  if (!empty($hidden_content_types)) {
    $and = db_and();
    foreach ($hidden_content_types as $index => $content_type) {
      $and->condition('n.type', $content_type, '!=');
    }
    $query->condition($and);
  }
}
