<?php
/**
 * @file
 * Add a close button to allow manual hiding of Drupal's status messages.
 */

/**
 *  Implements hook_init().
 */
function dismiss_messages_init() {
  drupal_add_css(drupal_get_path('module', 'dismiss_messages') . '/dismiss_messages.css');
  drupal_add_js(drupal_get_path('module', 'dismiss_messages') . '/dismiss_messages.js');
}

/*
 * Implementation of hook_theme_registry_alter
 */
function dismiss_messages_theme_registry_alter(&$theme_registry) {
  // override theme_status_messages()
  $theme_registry['status_messages']['function'] = "theme_dismiss_messages";
}

/*
 * Like core theme_status_messages(), but with "close" button
 */
function theme_dismiss_messages($variables) {
  $display = $variables['display'];
  $output = '';

  $close_button_image = drupal_get_path('module', 'dismiss_messages') . '/message-close.png';

  $status_heading = array(
    'status' => t('Status message'),
    'error' => t('Error message'),
    'warning' => t('Warning message'),
  );
  foreach (drupal_get_messages($display) as $type => $messages) {
    $output .= "<div class=\"messages $type\">\n";
    $output .= "<div class=\"dismiss-message\"><a href=\"#\"><img alt=\"close\" title=\"hide this message\" src=\"/$close_button_image\" /></a></div>\n";
    if (!empty($status_heading[$type])) {
      $output .= '<h2 class="element-invisible">' . $status_heading[$type] . "</h2>\n";
    }
    if (count($messages) > 1) {
      $output .= " <ul>\n";
      foreach ($messages as $message) {
        $output .= '  <li>' . $message . "</li>\n";
      }
      $output .= " </ul>\n";
    }
    else {
      $output .= $messages[0];
    }
    $output .= "</div>\n";
  }
  $output .= '

  ';

  return $output;
}