<?php
/**
 * @file
 */

/**
 * Implements hook_form_FORM_ID_alter() for garden_node_form.
 */
function gardenwalk_application_form_garden_node_form_alter(&$form, &$form_state, $form_id) {
  //dsm($form);
  global $user;
  if ($user->uid == 0) {
    drupal_set_title(t('2012 GardenWalk Garden Application'));

    // Hide fields
    remove_field($form, 'body');
    remove_field($form, 'field_gardenwalk_year');
    remove_field($form, 'field_handicap_accessible');
    remove_field($form, 'field_accessibility_notes');

    $ordered_groups = array();
    foreach ($form['#groups'] as $group_id => $group) {
      if ($group_id != 'group_main') {
        $ordered_groups[$group->weight] = $group_id;
      }
    }
    ksort($ordered_groups);
    $idx = 0;
    foreach ($ordered_groups as $weight => $group_id) {
      $form['#groups'][$group_id]->label = ++$idx . '. ' . $form['#groups'][$group_id]->label;
    }

    // Better descriptions for field titles
    $form['field_yard_areas']['und']['#title'] = 'Yard areas you will allow public access to:';
    $form['field_ok']['und']['#title'] = 'Is it okay to take photos of your garden for publicity purposes?';
    $form['field_gardenwalk_past_year']['und']['#title'] = 'Was your garden included in GardenWalk 2011?';

    $form['actions']['submit']['#submit'][] = 'gardenwalk_application_submit'; // Custom submit handler
    $form['actions']['submit']['#value'] = 'Submit application'; // Save button
    $form['agreement'] = array(
      '#type' => 'fieldset',
      '#collapsible' => FALSE,
      '#weight' => 4,
    );
    $form['agreement']['text'] = array(
      '#markup' => t('I agree to make my garden accessible July 21st & 22nd, 
      2012, (11am - 5pm,) and understand that the selling of any items during 
      the event will prevent my participation in future events.'),
    );
    $form['agreement']['agree'] = array(
       '#type' => 'checkbox',
       '#title' => t('I agree'),
       '#required' => TRUE,
     );
  } else {
    //unset($form['field_yard_areas']['und']['#description']);
  }
  //dsm($form);
  return $form;
}


/**
 * Removes a field from the node form, both at top-level and within the
 * field groups.
 */
function remove_field(&$form, $field_name) {
  unset($form[$field_name]);
  $groups_root = $form['#groups'];
  foreach ($groups_root as $group_name => $group) {
    $child_key = array_search($field_name, $group->children);
    if ($child_key !== FALSE) {
      unset($form['#groups'][$group_name]->children[$child_key]);
    }
  }
}

/**
 * Custom submit handler for garden submit
 */
function gardenwalk_application_submit($form, &$form_state) {
  $form_state['redirect'] = 'application-submitted';
}

/**
 * Implements hook_theme().
 *
 * Sets a custom template for the garden edit form.
 */
function gardenwalk_application_theme($existing, $type, $theme, $path) {
  return array(
    'garden_node_form' => array(
      'arguments' => array(
          'form' => NULL,
      ),
      'template' => 'node-garden-edit',
      'render element' => 'form',
    ),
  );
}

/**
 * Preprocessor for theme('garden_node_form').
 */
function gardenwalk_application_preprocess_garden_node_form(&$variables) {
  global $user;
  if ($user->uid == 0) {
    $variables['instructions'] = '<p>Want to show your garden in GardenWalk 2012?</p>
      <p>If you live in one of the GardenWalk 2012 neighborhoods, please fill out 
      the form below to apply. A garden finder from your neighborhood will get back 
      to you. If you\'re interested in volunteering or supporting GardenWalk Cleveland 
      in some other way, check out our <a href="/get-involved">Get Involved</a> page.</p>';
  } else {
    $variables['instructions'] = '';
  }
}
?>