<?php
/**
 * @file
 */

/**
 * Implements hook_form_FORM_ID_alter() for garden_node_form.
 */
function gardenwalk_application_form_garden_node_form_alter(&$form, &$form_state, $form_id) {
  //dsm($form);
  global $user;
  if ($user->uid == 0) {
    drupal_set_title(t('2012 GardenWalk Garden Application'));
  }
  return $form;
}

function gardenwalk_application_theme($existing, $type, $theme, $path) {
  return array(
    'garden_node_form' => array(
      'arguments' => array(
          'form' => NULL,
      ),
      'template' => 'node-garden-edit',
      'render element' => 'form',
    ),
  );
}

/**
 * Preprocessor for theme('garden_node_form').
 */
function gardenwalk_application_preprocess_garden_node_form(&$variables) {
  global $user;
  if ($user->uid == 0) {
    $variables['instructions'] = '<p>Want to show your garden in GardenWalk 2012?</p>
      <p>If you live in one of the GardenWalk 2012 neighborhoods, please fill out 
      the form below to apply. A garden finder from your neighborhood will get back 
      to you. If you\'re interested in volunteering or supporting GardenWalk Cleveland 
      in some other way, check out our Get Involved page.</p>';
  } else {
    $variables['instructions'] = '';
  }
}
?>